### ISSUE TITLE
 Unable to Determine connectAuth Connection Issues

### ISSUE THREAD

**Issue by liuguan1984** [vadia/smb_connect#1]
When I use connectAuth to establish a connection, as long as the IP is correct, even if the username and password are incorrect or empty, I cannot get any connection error information.

Previously, it was possible to catch errors using try, but now it seems this no longer works. Currently, I can only observe connection details through the debugPrint toggle.

I hope to handle connection error information properly in the code and classify the errors for processing.

**Comment by vadia** [comment]
@liuguan1984 Implementation for smb2 protocol not throw exception SmbAuthException. Fixed in 0.0.6 already available.

**Comment by liuguan1984** [comment]
Thank you! As you suggested, I have updated to version 0.0.7, but when I use the following code, I still cannot catch the error.
SmbConnect.connectAuth(...).then((result) {
      print('success');
    }).catchError((error) {
      print('error');
    });
I hope to receive help again, thank you!

**Comment by vadia** [comment]
@liuguan1984 SmbConnect.connectAuth esteblish connection, but a session is created with first request share folder.
How you can fix it for now:
```dart
try {
  var connect = await SmbConnect.connectAuth(...);
  var res = await connect.file("/$share/");    
} catch (e) {
  print(e);
}
```
I will try to fix this in the next version.

**Comment by liuguan1984** [comment]
It's OK!Thank u.

**Comment by vadia** [comment]
Fixed in version 0.0.9.
Now auth checking while connectAuth:

```dart
try {
  var connect = await SmbConnect.connectAuth(...);
} catch (e) {
  print(e);
}
```
